### PR TITLE
Remove global variables and check for API errors

### PR DESCRIPTION
**Pull request by colesbury**
Remove global variables, check for API errors, and some small changes:
- The ncclComm gc hook was not called on the correct communicators
- In reduce and bcast `root` did not select the correct tensor if
  the input was not in 1, 2, 3, etc. order.
- Trigger an error if the user specifies an invalid root
- Use the new-style module semantics: require 'nccl' now returns
  the nccl module

### CODE REVIEW

**Comment by ngimel** [comment]
Thanks!

**Comment by ngimel** [comment]
Wait, actually in reduce and broadcast `root` is selected as `devices[root]` by design - if `root = 1` than first tensor in the table is the root whatever its device. With this commit DataParallelTable in cunn will have to be changed, so I'd rather back this one out. Do you mind?

**Comment by colesbury** [comment]
I don't think `devices[root]` is correct, because internally NCCL uses root to index into the `ringFromUser`:
https://github.com/NVIDIA/nccl/blob/master/src/broadcast.cu#L291

`DataParallelTable` is currently buggy when GPU assignments aren't in 1,2,3 order. I'm working on merging Facebook's fixes for this (probably tomorrow), but the first module in DataParallelTable should be the root (whatever it's device).

**Comment by ngimel** [comment]
You are right. Thanks!

**Pull request merged**
